---
- name: Install Docker
  hosts: all
  tasks:
  - name: Install Docker packages 
    yum:
      name: docker
      state: present
  - name: Ensure Docker is running
    service:
      name: docker 
      state: started