---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
  - name: Install Docker packages 
    yum:
      name: docker
      state: present
  - name: Ensure Docker is running
    service:
      name: docker
      enabled: yes 
      state: started
      
  - name: Download application
    shell: wget https://github.com/bdobay/IPweatherapp/archive/refs/heads/master.zip
    
  - name: Unzip
    shell: unzip master.zip   

  - name: Build Docker image of application
    shell: sudo docker build -t my-flask-app .
    args:
        chdir: "./IPweatherapp-master"
       

  - name: Run Docker build
    shell: sudo docker run -p 5004:5005 --name my-flask-app -d my-flask-app


    

    
       
    
              